# -*- coding: utf-8 -*-
"""scratchpad

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/empty.ipynb
"""

import pandas as pd
import numpy as np
import os

# =====================================================================
# 1. Process Kitchen Display Speed of Service Dataset
# =====================================================================

input_file_path = '/content/Subway Database(Sheet1).csv'

if os.path.exists(input_file_path):
    print("Processing Kitchen Display Speed of Service dataset...")
    # Load original dataset
    kitchen_df = pd.read_csv(input_file_path)

    # Drop any 'Unnamed' columns completely
    kitchen_df = kitchen_df.loc[:, ~kitchen_df.columns.str.contains('^Unnamed', case=False, na=False)]

    # Ensure we drop completely empty rows and export text artifacts (like "Page -1 of 1")
    kitchen_df = kitchen_df.dropna(subset=['Date', 'Time_Period'], how='all')
    kitchen_df = kitchen_df[~kitchen_df['Date'].astype(str).str.contains('Page|Total', case=False, na=False)]

    # Extract and export 'Total' or 'Totals' rows (day totals) if they exist
    # (Re-reading freshly to catch totals cleanly before filtering)
    full_raw = pd.read_csv(input_file_path)
    day_totals = full_raw[full_raw['Date'].astype(str).str.contains('Total', case=False, na=False)]
    day_totals = day_totals.loc[:, ~day_totals.columns.str.contains('^Unnamed', case=False, na=False)]
    day_totals.to_csv('day_totals.csv', index=False)
    print(f"- Extracted {len(day_totals)} day total rows and saved to 'day_totals.csv'")

    # Further clean dataset: convert 'Number_Of_Orders' to numeric and drop NaN rows
    df_final_cleaned = kitchen_df.copy()
    df_final_cleaned['Number_Of_Orders'] = pd.to_numeric(df_final_cleaned['Number_Of_Orders'], errors='coerce')
    df_final_cleaned = df_final_cleaned.dropna(subset=['Number_Of_Orders', 'Date', 'Time_Period'])

    # Export the final cleaned kitchen dataset
    df_final_cleaned.to_csv('df_final_cleaned.csv', index=False)
    print(f"- Cleaned kitchen dataset ({len(df_final_cleaned)} rows) and saved to 'df_final_cleaned.csv'")

    # =====================================================================
    # 2. Process Subway Database Dataset
    # =====================================================================

    print("\nProcessing Subway Database dataset...")
    subway_df = pd.read_csv(input_file_path)

    # Drop any 'Unnamed' columns
    subway_df = subway_df.loc[:, ~subway_df.columns.str.contains('^Unnamed', case=False, na=False)]

    # Drop completely empty rows, artifact rows, and rows containing 'Total' or 'Totals'
    subway_df = subway_df.dropna(subset=['Date', 'Time_Period'], how='all')
    subway_df = subway_df[~subway_df['Date'].astype(str).str.contains('Page|Total', case=False, na=False)]

    # Convert and filter strictly for valid rows
    subway_df['Number_Of_Orders'] = pd.to_numeric(subway_df['Number_Of_Orders'], errors='coerce')
    subway_df = subway_df.dropna(subset=['Number_Of_Orders', 'Date', 'Time_Period'])

    # Add 'Location' and 'Order_Type' columns
    subway_df['Location'] = 'Subway'
    subway_df['Order_Type'] = 'Kiosk'

    # Export the modified Subway dataset
    subway_df.to_csv('Subway_Kiosk.csv', index=False)
    print(f"- Added 'Location' and 'Order_Type' columns and saved to 'Subway_Kiosk.csv'")

    # =====================================================================
    # 3. Display Previews
    # =====================================================================
    print("\n--- Previews ---")
    print("\nDay Totals Preview:")
    display(day_totals.head(5))

    print("\nFinal Cleaned Kitchen Dataset Preview:")
    display(df_final_cleaned.head(5))

    print("\nSubway Kiosk Dataset Preview:")
    display(subway_df.head(5))
else:
    print(f"Warning: The file '{input_file_path}' was not found. Skipping Subway database processing.")

import pandas as pd
import numpy as np
import os

def process_pipeline(raw_data_path, kiosk_data_path):
    # Verify that the raw mobile data file exists before starting
    if not os.path.exists(raw_data_path):
        print(f"Error: Raw mobile data file '{raw_data_path}' was not found. Pipeline cannot proceed.")
        return

    # --- STEP 1: Process raw ticket data & Split by Location ---
    print("Starting Step 1: Processing raw data...")
    df = pd.read_csv(raw_data_path)

    # Rename the column ' Completed Date_Time' to 'Completed_Date_Time'
    df = df.rename(columns={' Completed Date_Time': 'Completed_Date_Time'})

    def split_times(df_input):
        df_input.columns = df_input.columns.str.strip()

        # Ensure datetime types
        if 'TransactionDateTime' in df_input.columns and not pd.api.types.is_datetime64_any_dtype(df_input['TransactionDateTime']):
            df_input['TransactionDateTime'] = pd.to_datetime(df_input['TransactionDateTime'], errors='coerce')

        if 'Completed_Date_Time' in df_input.columns and not pd.api.types.is_datetime64_any_dtype(df_input['Completed_Date_Time']):
            df_input['Completed_Date_Time'] = pd.to_datetime(df_input['Completed_Date_Time'], errors='coerce')

        # Extract Date and Time components
        if 'TransactionDateTime' in df_input.columns:
            df_input['TransactionDate'] = df_input['TransactionDateTime'].dt.date
            df_input['StartTime'] = df_input['TransactionDateTime'].dt.time
            df_input = df_input.drop(columns=['TransactionDateTime'])

        if 'Completed_Date_Time' in df_input.columns:
            df_input['FinishedTime'] = df_input['Completed_Date_Time'].dt.time
            df_input = df_input.drop(columns=['Completed_Date_Time'])

        return df_input

    df = split_times(df)
    df.columns = df.columns.str.strip()

    # Calculate elapsed time in seconds
    df['Elapsed_Time'] = (pd.to_timedelta(df['FinishedTime'].astype(str)) - pd.to_timedelta(df['StartTime'].astype(str))).dt.total_seconds()
    df = df[df['Elapsed_Time'] >= 0]

    # Save Complete_Data.csv
    df.to_csv('Complete_Data.csv', index=False)
    print("Complete_Data.csv has been created in the current directory.")

    # Save separate files for each location
    unique_locations = df['Location'].unique()
    for location in unique_locations:
        location_df = df[df['Location'] == location]
        sanitized_location = location.replace('/', '_').replace('\\', '_').replace(':', '_').replace('*', '_').replace('?', '_').replace('"', '_').replace('<', '_').replace('>', '_').replace('|', '_')
        filename = f"{sanitized_location}_Data.csv"
        location_df.to_csv(filename, index=False)
        print(f"Created '{filename}' with data for {location}")

    # --- STEP 2: Aggregate & Format into 15-Minute Intervals ---
    print("\nStarting Step 2: Resampling and formatting into 15-minute intervals...")
    df_complete = pd.read_csv('Complete_Data.csv', low_memory=False)

    # Re-combine to actual datetime objects for resampling
    df_complete['DateTime'] = pd.to_datetime(df_complete['TransactionDate'].astype(str) + ' ' + df_complete['StartTime'].astype(str), errors='coerce')
    df_complete = df_complete.dropna(subset=['DateTime'])

    df_complete['Interval_Start'] = df_complete['DateTime'].dt.floor('15min')

    # Define the aggregation logic (without Avg_No_Items)
    agg_funcs = {
        'TransactionDate': 'size',   # Number_Of_Orders
        'Elapsed_Time': ['mean', 'min', 'max']
    }

    df_grouped = df_complete.groupby(['Interval_Start', 'Location']).agg(agg_funcs).reset_index()
    df_grouped.columns = [
        'Interval_Start',
        'Location',
        'Number_Of_Orders',
        'Avg_Bump_Time',
        'Low_Bump',
        'High_Bump'
    ]

    # Clean and round numeric columns
    df_grouped['Avg_Bump_Time'] = df_grouped['Avg_Bump_Time'].fillna(0).round().astype(int)
    df_grouped['Low_Bump'] = df_grouped['Low_Bump'].fillna(0).round().astype(int)
    df_grouped['High_Bump'] = df_grouped['High_Bump'].fillna(0).round().astype(int)

    # Format extra time/day columns
    df_grouped['Date'] = df_grouped['Interval_Start'].dt.strftime('%-m/%-d/%Y')
    start_time_str = df_grouped['Interval_Start'].dt.strftime('%-H:%M')
    end_time_str = (df_grouped['Interval_Start'] + pd.Timedelta(minutes=14)).dt.strftime('%-H:%M')
    df_grouped['Time_Period'] = start_time_str + ' - ' + end_time_str
    df_grouped['Days'] = df_grouped['Interval_Start'].dt.strftime('%a')
    df_grouped['Order_Type'] = 'Mobile'

    # Order columns (removed 'Avg_No_Items')
    final_cols = ['Date', 'Time_Period', 'Number_Of_Orders', 'Avg_Bump_Time', 'Low_Bump', 'High_Bump', 'Days', 'Location', 'Order_Type']
    df_formatted = df_grouped[final_cols]

    # Save to Mobile_15.csv
    df_formatted.to_csv('Mobile_15.csv', index=False)
    print("Mobile_15.csv has been saved.")

    # --- STEP 3: Combine with Subway Kiosk Data ---
    if os.path.exists(kiosk_data_path):
        print("\nStarting Step 3: Appending Kiosk Data...")
        df_mobile = pd.read_csv('Mobile_15.csv')
        df_kiosk = pd.read_csv(kiosk_data_path)

        # In case the kiosk dataset has 'Avg_No_Items', we drop it if it exists
        if 'Avg_No_Items' in df_kiosk.columns:
            df_kiosk = df_kiosk.drop(columns=['Avg_No_Items'])

        df_complete_orders = pd.concat([df_mobile, df_kiosk], ignore_index=True)
        df_complete_orders.to_csv('Complete_Orders.csv', index=False)

        print("The merged dataset has been exported to 'Complete_Orders.csv'")
        print(f"Total rows in Mobile_15.csv: {len(df_mobile)}")
        print(f"Total rows in Subway_Kiosk.csv: {len(df_kiosk)}")
        print(f"Total rows in Complete_Orders.csv: {len(df_complete_orders)}")

        # Verify line counts of final Mobile_15.csv
        with open('Mobile_15.csv', 'r', encoding='utf-8', errors='ignore') as f:
            mobile_line_count = sum(1 for _ in f)
        print(f"The file 'Mobile_15.csv' has {mobile_line_count:,} lines.")

        display(df_complete_orders.tail(10))
    else:
        print(f"\nSkipped Step 3: Kiosk dataset '{kiosk_data_path}' was not found. Saving only Mobile results.")
        df_mobile = pd.read_csv('Mobile_15.csv')
        df_mobile.to_csv('Complete_Orders.csv', index=False)
        print("Copied 'Mobile_15.csv' directly to 'Complete_Orders.csv' since Kiosk data was missing.")

# Execute entire pipeline checking for the file
raw_input_path = '/content/Mobile Ticket Time Data(in).csv'
kiosk_input_path = '/content/Subway_Kiosk.csv'

process_pipeline(raw_input_path, kiosk_input_path)
