# -*- coding: utf-8 -*-
"""DS_Data_Cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17WI0_aBvzPkXRLyTZZFeNsTDTiGkrdit
"""

import pandas as pd

def process_and_split_data(file_path):
    """
    Processes a CSV file, calculates elapsed time, and splits data by location.

    Args:
        file_path (str): The path to the input CSV file.
    """
    df = pd.read_csv(file_path)

    # Rename the column ' Completed Date_Time' to 'Completed_Date_Time'
    df = df.rename(columns={' Completed Date_Time': 'Completed_Date_Time'})

    def split_times(df_input):
        # Clean up column names by stripping whitespace
        df_input.columns = df_input.columns.str.strip()

        # Ensure TransactionDateTime is datetime type if not already
        if 'TransactionDateTime' in df_input.columns and not pd.api.types.is_datetime64_any_dtype(df_input['TransactionDateTime']):
            df_input['TransactionDateTime'] = pd.to_datetime(df_input['TransactionDateTime'], errors='coerce')

        # Ensure Completed_Date_Time is datetime type if not already
        if 'Completed_Date_Time' in df_input.columns and not pd.api.types.is_datetime64_any_dtype(df_input['Completed_Date_Time']):
            df_input['Completed_Date_Time'] = pd.to_datetime(df_input['Completed_Date_Time'], errors='coerce')

        # Extract date into a new column 'TransactionDate' if 'TransactionDateTime' exists
        if 'TransactionDateTime' in df_input.columns:
            df_input['TransactionDate'] = df_input['TransactionDateTime'].dt.date

        # Extract time into a new column 'StartTime' if 'TransactionDateTime' exists
        if 'TransactionDateTime' in df_input.columns:
            df_input['StartTime'] = df_input['TransactionDateTime'].dt.time

        # Drop the original 'TransactionDateTime' column if it exists
        if 'TransactionDateTime' in df_input.columns:
            df_input = df_input.drop(columns=['TransactionDateTime'])

        # Extract time into a new column 'FinishedTime' from 'Completed_Date_Time' if it exists
        if 'Completed_Date_Time' in df_input.columns:
            df_input['FinishedTime'] = df_input['Completed_Date_Time'].dt.time

        # Drop the original 'Completed_Date_Time' column if it exists
        if 'Completed_Date_Time' in df_input.columns:
            df_input = df_input.drop(columns=['Completed_Date_Time'])

        return df_input

    # Call the function with the DataFrame
    df = split_times(df)

    df.columns = df.columns.str.strip()

    # Convert time columns to string first to handle potential NaT values gracefully before timedelta conversion
    df['Elapsed_Time'] = (pd.to_timedelta(df['FinishedTime'].astype(str)) - pd.to_timedelta(df['StartTime'].astype(str))).dt.total_seconds()

    df = df[df['Elapsed_Time'] >= 0]

    df.to_csv('Complete_Data.csv', index=False)
    print("Complete_Data.csv has been created in the current directory.")

    # Get all unique locations
    unique_locations = df['Location'].unique()

    # Create a new CSV file for each unique location
    for location in unique_locations:
        # Filter the DataFrame for the current location
        location_df = df[df['Location'] == location]

        # Sanitize location name for filename (replace characters that might cause issues)
        sanitized_location = location.replace('/', '_').replace('\\', '_').replace(':', '_').replace('*', '_').replace('?', '_').replace('"', '_').replace('<', '_').replace('>', '_').replace('|', '_')

        # Define the filename
        filename = f"{sanitized_location + "_Data"}.csv"

        # Save to CSV without the index
        location_df.to_csv(filename, index=False)

        print(f"Created '{filename}' with data for {location}")

# Replace 'your_file_path.csv' with the actual path to your CSV file
process_and_split_data('/content/Mobile Ticket Time Data(in).csv')